In [28]:
import warnings
warnings.filterwarnings("ignore")

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [29]:
df = pd.read_csv("flipkart_mobile_phones_data.csv")

In [30]:
df

,Unnamed: 0,Product Name,Sale & Actual Price,Raview & Rattings,Offer,Camera,Memory,Battery,Display,Ratting Number
0,0,"realme P4x 5G (Lake Green, 128 GB)","₹16,499₹17,9998% off","7,161 Ratings & 549 Reviews",8% off,50MP + 2MP | 8MP Front Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.07 cm (6.72 inch) Full HD+ Display,4.4
1,1,"Coolpad CP12 Neo (Gold, 64 GB)","₹7,299₹9,99927% off",NaN,27% off,13MP Rear Camera | 5MP Front Camera,8 GB RAM | 64 GB ROM | Expandable Upto 512 GB,5000 mAh Battery,16.66 cm (6.56 inch) Display,NaN
2,2,"MOTOROLA g06 power (Pantone tapestry, 64 GB)","₹7,999₹9,99920% off","6,394 Ratings & 382 Reviews",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3
3,3,"MOTOROLA g06 power (Pantone Laurel Oak, 64 GB)","₹7,999₹9,99920% off","6,394 Ratings & 382 Reviews",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3
4,4,"MOTOROLA g06 power (Pantone Tendril, 64 GB)","₹7,999₹9,99920% off","6,394 Ratings & 382 Reviews",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3
...,...,...,...,...,...,...,...,...,...,...
979,979,"realme 15 5G (Flowing Silver, 256 GB)","₹30,999₹31,9993% off","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4
980,980,"realme 15 5G (Silk Pink, 256 GB)","₹30,999₹31,9993% off","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4
981,981,"realme 15 5G (Velvet Green, 256 GB)","₹30,999₹31,9993% off","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4
982,982,"realme 15 5G (Velvet Green, 128 GB)","₹28,999₹29,9993% off","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 128 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4
983,983,"realme 15 5G (Silk Pink, 128 GB)","₹28,999₹29,9993% off","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 128 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4

In [31]:
df = df.drop("Unnamed: 0", axis = 1)

In [32]:
df["Sale & Actual Price"][0].split(df["Offer"][0])[0].split("₹")[1].replace(",", "")

'16499'

In [33]:
df.iloc[219]

Product Name           MOTOROLA Edge 60 Pro (Pantone Shadow, 256 GB)
Sale & Actual Price                            ₹29,999₹36,99918% off
Raview & Rattings                     46,783 Ratings & 3,440 Reviews
Offer                                                        18% off
Camera                        50MP + 50MP + 10MP | 50MP Front Camera
Memory                                         8 GB RAM | 256 GB ROM
Battery                                             6000 mAh Battery
Display                                  17.02 cm (6.7 inch) Display
Ratting Number                                                   4.3
Name: 219, dtype: object

In [34]:
sale_price = []
actual_price = []

for i in range(df.shape[0]):
    try:
        a = df["Sale & Actual Price"][i].split(df["Offer"][i])[0].split("₹")[1]
        sale_price.append(int(a.replace(",", "")))

        try:
            b = df["Sale & Actual Price"][i].split(df["Offer"][i])[0].split("₹")[2]
        except IndexError:
            b = a

        actual_price.append(int(b.replace(",", "")))
    except IndexError:
        sale_price.append(df["Sale & Actual Price"][i])
        actual_price.append(df["Sale & Actual Price"][i])

In [35]:
df["Sale Price"] = sale_price
df["Actual Price"] = actual_price

In [36]:
df = df.drop("Sale & Actual Price", axis = 1)

In [37]:
splitted_cols = df['Raview & Rattings'].str.split("&", expand=True)

In [38]:
df

,Product Name,Raview & Rattings,Offer,Camera,Memory,Battery,Display,Ratting Number,Sale Price,Actual Price
0,"realme P4x 5G (Lake Green, 128 GB)","7,161 Ratings & 549 Reviews",8% off,50MP + 2MP | 8MP Front Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.07 cm (6.72 inch) Full HD+ Display,4.4,16499,17999
1,"Coolpad CP12 Neo (Gold, 64 GB)",NaN,27% off,13MP Rear Camera | 5MP Front Camera,8 GB RAM | 64 GB ROM | Expandable Upto 512 GB,5000 mAh Battery,16.66 cm (6.56 inch) Display,NaN,7299,9999
2,"MOTOROLA g06 power (Pantone tapestry, 64 GB)","6,394 Ratings & 382 Reviews",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3,7999,9999
3,"MOTOROLA g06 power (Pantone Laurel Oak, 64 GB)","6,394 Ratings & 382 Reviews",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3,7999,9999
4,"MOTOROLA g06 power (Pantone Tendril, 64 GB)","6,394 Ratings & 382 Reviews",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3,7999,9999
...,...,...,...,...,...,...,...,...,...,...
979,"realme 15 5G (Flowing Silver, 256 GB)","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,30999,31999
980,"realme 15 5G (Silk Pink, 256 GB)","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,30999,31999
981,"realme 15 5G (Velvet Green, 256 GB)","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,30999,31999
982,"realme 15 5G (Velvet Green, 128 GB)","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 128 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,28999,29999
983,"realme 15 5G (Silk Pink, 128 GB)","10,672 Ratings & 863 Reviews",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 128 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,28999,29999

In [39]:
splitted_cols.value_counts()

0                1
7,161 Ratings     549 Reviews      20
6,922 Ratings     406 Reviews      10
43,589 Ratings    2,715 Reviews     9
44,538 Ratings    2,650 Reviews     9
16,259 Ratings    869 Reviews       8
                                   ..
4,284 Ratings     306 Reviews       1
34 Ratings        1 Reviews         1
2,300 Ratings     163 Reviews       1
294 Ratings       11 Reviews        1
3,899 Ratings     194 Reviews       1
Name: count, Length: 351, dtype: int64

In [40]:
splitted_cols [0] = splitted_cols[0].fillna('7,161 Ratings')

In [41]:
splitted_cols[1]=splitted_cols[1].fillna(' 549  Reviews')

In [42]:
df["No of Reviews"] = splitted_cols[0].str.replace(",", "").str.extract(r"(\d+)").astype(int)
df["No of Rattings"] = splitted_cols[1].str.replace(",", "").str.extract(r"(\d+)").astype(int)

In [43]:
final_df = df.drop("Raview & Rattings", axis = 1)

In [44]:
final_df.to_csv("processed_flipkart_mobile_phones_data.csv")

In [45]:
final_df.shape

(984, 11)

In [47]:
final_df

,Product Name,Offer,Camera,Memory,Battery,Display,Ratting Number,Sale Price,Actual Price,No of Reviews,No of Rattings
0,"realme P4x 5G (Lake Green, 128 GB)",8% off,50MP + 2MP | 8MP Front Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.07 cm (6.72 inch) Full HD+ Display,4.4,16499,17999,7161,549
1,"Coolpad CP12 Neo (Gold, 64 GB)",27% off,13MP Rear Camera | 5MP Front Camera,8 GB RAM | 64 GB ROM | Expandable Upto 512 GB,5000 mAh Battery,16.66 cm (6.56 inch) Display,NaN,7299,9999,7161,549
2,"MOTOROLA g06 power (Pantone tapestry, 64 GB)",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3,7999,9999,6394,382
3,"MOTOROLA g06 power (Pantone Laurel Oak, 64 GB)",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3,7999,9999,6394,382
4,"MOTOROLA g06 power (Pantone Tendril, 64 GB)",20% off,50MP Rear Camera | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 1 TB,7000 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.3,7999,9999,6394,382
...,...,...,...,...,...,...,...,...,...,...,...
979,"realme 15 5G (Flowing Silver, 256 GB)",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,30999,31999,10672,863
980,"realme 15 5G (Silk Pink, 256 GB)",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,30999,31999,10672,863
981,"realme 15 5G (Velvet Green, 256 GB)",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,30999,31999,10672,863
982,"realme 15 5G (Velvet Green, 128 GB)",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 128 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,28999,29999,10672,863
983,"realme 15 5G (Silk Pink, 128 GB)",3% off,50MP + 8MP | 50MP Front Camera,8 GB RAM | 128 GB ROM,7000 mAh Battery,17.27 cm (6.8 inch) Display,4.4,28999,29999,10672,863